/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AccountReceivableType = 'rent' | 'fee' | 'other';

export const AccountReceivableType = {
    Rent: 'rent' as AccountReceivableType,
    Fee: 'fee' as AccountReceivableType,
    Other: 'other' as AccountReceivableType
};

