/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AccountReceivableIncomeType = 'fee' | 'merchandise' | 'other' | 'rental';

export const AccountReceivableIncomeType = {
    Fee: 'fee' as AccountReceivableIncomeType,
    Merchandise: 'merchandise' as AccountReceivableIncomeType,
    Other: 'other' as AccountReceivableIncomeType,
    Rental: 'rental' as AccountReceivableIncomeType
};

