/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountReceivableResponse { 
    /**
     * Ledger ID.
     */
    ledgerId: string;
    /**
     * Organization ID.
     */
    orgId: string;
    /**
     * Site ID.
     */
    siteId: string;
    /**
     * Location ID.
     */
    locationId: string;
    /**
     * Opening balance.
     */
    openingBalance: number;
    /**
     * Closing balance.
     */
    closingBalance: number;
    /**
     * Fee income.
     */
    feeIncome: number;
    /**
     * Merchandise income.
     */
    merchandiseIncome: number;
    /**
     * Rental income.
     */
    rentalIncome: number;
    /**
     * Other income.
     */
    otherIncome: number;
}

