/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountReceivableIncomeType } from './accountReceivableIncomeType';


export interface AccountReceivableIncome { 
    incomeType: AccountReceivableIncomeType;
    /**
     * Total.
     */
    incomeTotal: number;
}
export namespace AccountReceivableIncome {
}


