/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CheckAssetType = 'ach_debit' | 'afterpay_clearpay' | 'alipay' | 'amex_credit' | 'amex_debit' | 'apple_pay' | 'bacs_debit' | 'bancontact' | 'bank_transfer' | 'cash' | 'check' | 'diners_card' | 'discover_credit' | 'discover_debit' | 'eps' | 'giropay' | 'google_pay' | 'ideal' | 'klarna' | 'mastercard_credit' | 'mastercard_debit' | 'multibanco' | 'oxxo' | 'other' | 'p24' | 'paypal' | 'sepa_debit' | 'sofort' | 'visa_credit' | 'visa_debit' | 'wechat_pay';

export const CheckAssetType = {
    AchDebit: 'ach_debit' as CheckAssetType,
    AfterpayClearpay: 'afterpay_clearpay' as CheckAssetType,
    Alipay: 'alipay' as CheckAssetType,
    AmexCredit: 'amex_credit' as CheckAssetType,
    AmexDebit: 'amex_debit' as CheckAssetType,
    ApplePay: 'apple_pay' as CheckAssetType,
    BacsDebit: 'bacs_debit' as CheckAssetType,
    Bancontact: 'bancontact' as CheckAssetType,
    BankTransfer: 'bank_transfer' as CheckAssetType,
    Cash: 'cash' as CheckAssetType,
    Check: 'check' as CheckAssetType,
    DinersCard: 'diners_card' as CheckAssetType,
    DiscoverCredit: 'discover_credit' as CheckAssetType,
    DiscoverDebit: 'discover_debit' as CheckAssetType,
    Eps: 'eps' as CheckAssetType,
    Giropay: 'giropay' as CheckAssetType,
    GooglePay: 'google_pay' as CheckAssetType,
    Ideal: 'ideal' as CheckAssetType,
    Klarna: 'klarna' as CheckAssetType,
    MastercardCredit: 'mastercard_credit' as CheckAssetType,
    MastercardDebit: 'mastercard_debit' as CheckAssetType,
    Multibanco: 'multibanco' as CheckAssetType,
    Oxxo: 'oxxo' as CheckAssetType,
    Other: 'other' as CheckAssetType,
    P24: 'p24' as CheckAssetType,
    Paypal: 'paypal' as CheckAssetType,
    SepaDebit: 'sepa_debit' as CheckAssetType,
    Sofort: 'sofort' as CheckAssetType,
    VisaCredit: 'visa_credit' as CheckAssetType,
    VisaDebit: 'visa_debit' as CheckAssetType,
    WechatPay: 'wechat_pay' as CheckAssetType
};

