/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneralLedgerEntryType } from './generalLedgerEntryType';
import { CreateGeneralLedgerLineItemRequest } from './createGeneralLedgerLineItemRequest';


export interface CreateGeneralLedgerEntryRequest { 
    /**
     * ID of the Ledger
     */
    ledgerId: string;
    /**
     * ID of the Location
     */
    locationId: string;
    /**
     * description of the entry
     */
    description?: string;
    /**
     * tag of the entry
     */
    tag: string;
    generalLedgerEntryType: GeneralLedgerEntryType;
    /**
     * The date the change was made.
     */
    entryDate: string;
    /**
     * The line items of the entry
     */
    lineItems: Array<CreateGeneralLedgerLineItemRequest>;
}
export namespace CreateGeneralLedgerEntryRequest {
}


