/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneralLedgerAccountType } from './generalLedgerAccountType';


export interface CreateGeneralLedgerAccountRequest { 
    /**
     * Title of the account
     */
    title: string;
    /**
     * Description of the account
     */
    description?: string;
    /**
     * Alias for the account
     */
    alias?: string;
    generalLedgerAccountType: GeneralLedgerAccountType;
}
export namespace CreateGeneralLedgerAccountRequest {
}


