/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FeeIncomeType = 'administrative_fee' | 'electricity_fee' | 'inventory_fee' | 'late_fee' | 'lien_fee' | 'nsf_fee' | 'statement_fee' | 'unknown_fee';

export const FeeIncomeType = {
    AdministrativeFee: 'administrative_fee' as FeeIncomeType,
    ElectricityFee: 'electricity_fee' as FeeIncomeType,
    InventoryFee: 'inventory_fee' as FeeIncomeType,
    LateFee: 'late_fee' as FeeIncomeType,
    LienFee: 'lien_fee' as FeeIncomeType,
    NsfFee: 'nsf_fee' as FeeIncomeType,
    StatementFee: 'statement_fee' as FeeIncomeType,
    UnknownFee: 'unknown_fee' as FeeIncomeType
};

