/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GeneralLedgerAccountType = 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';

export const GeneralLedgerAccountType = {
    Asset: 'asset' as GeneralLedgerAccountType,
    Liability: 'liability' as GeneralLedgerAccountType,
    Equity: 'equity' as GeneralLedgerAccountType,
    Revenue: 'revenue' as GeneralLedgerAccountType,
    Expense: 'expense' as GeneralLedgerAccountType
};

