/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneralLedgerAccountResponse } from './generalLedgerAccountResponse';


export interface GetGeneralLedgerAccounts200Response { 
    data?: Array<GeneralLedgerAccountResponse>;
    success?: boolean;
    error?: object;
}

