/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneralLedgerAccountLineItemResponse } from './generalLedgerAccountLineItemResponse';


export interface GetGeneralLedgerAccountById200Response { 
    data?: Array<GeneralLedgerAccountLineItemResponse>;
    success?: boolean;
    error?: object;
}

