/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MerchandiseIncomeType = 'boxes' | 'locks' | 'equipment' | 'services' | 'truck_rental' | 'other';

export const MerchandiseIncomeType = {
    Boxes: 'boxes' as MerchandiseIncomeType,
    Locks: 'locks' as MerchandiseIncomeType,
    Equipment: 'equipment' as MerchandiseIncomeType,
    Services: 'services' as MerchandiseIncomeType,
    TruckRental: 'truck_rental' as MerchandiseIncomeType,
    Other: 'other' as MerchandiseIncomeType
};

