/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RentalIncomeType } from './rentalIncomeType';


export interface RentalIncomeEntryResponse { 
    /**
     * Rental Income Entry ID.
     */
    rentalIncomeEntryId: string;
    /**
     * Ledger ID.
     */
    ledgerId: string | null;
    /**
     * Organization ID.
     */
    orgId: string;
    /**
     * Site ID.
     */
    siteId: string;
    /**
     * Location ID.
     */
    locationId: string | null;
    /**
     * Amount.
     */
    amount: number;
    /**
     * Description.
     */
    description: string | null;
    rentalIncomeType: RentalIncomeType;
    /**
     * The start date of the entry.
     */
    startDate: string;
    /**
     * The end date of the entry.
     */
    endDate: string;
}
export namespace RentalIncomeEntryResponse {
}


